name: audio_spelling
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.5.4
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  


  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0



flutter:

  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/banner.png
    - assets/


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
  
flutter_native_splash:
  color: "#fcedd0"
  image: assets/splash.png 
  android_12:
    image: assets/splash.png  
    color: "#fcedd0"
    android_gravity: center
    branding: assets/banner.png
    branding_mode: bottom
    branding_bottom_padding: 24
  android: true